//
// Generated file, do not edit! Created by opp_msgtool 6.0 from TracedMessage.msg.
//

#ifndef __TRACEDMESSAGE_M_H
#define __TRACEDMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class TracedMessage;
/**
 * Class generated from <tt>TracedMessage.msg:15</tt> by opp_msgtool.
 * <pre>
 * //
 * // This program is free software: you can redistribute it and/or modify
 * // it under the terms of the GNU Lesser General Public License as published by
 * // the Free Software Foundation, either version 3 of the License, or
 * // (at your option) any later version.
 * // 
 * // This program is distributed in the hope that it will be useful,
 * // but WITHOUT ANY WARRANTY; without even the implied warranty of
 * // MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * // GNU Lesser General Public License for more details.
 * // 
 * // You should have received a copy of the GNU Lesser General Public License
 * // along with this program.  If not, see http://www.gnu.org/licenses/.
 * //
 * message TracedMessage
 * {
 *     simtime_t queueEnterTime;
 *     simtime_t queueLeaveTime;
 *     simtime_t finishedTime;
 * }
 * </pre>
 */
class TracedMessage : public ::omnetpp::cMessage
{
  protected:
    omnetpp::simtime_t queueEnterTime = SIMTIME_ZERO;
    omnetpp::simtime_t queueLeaveTime = SIMTIME_ZERO;
    omnetpp::simtime_t finishedTime = SIMTIME_ZERO;

  private:
    void copy(const TracedMessage& other);

  protected:
    bool operator==(const TracedMessage&) = delete;

  public:
    TracedMessage(const char *name=nullptr, short kind=0);
    TracedMessage(const TracedMessage& other);
    virtual ~TracedMessage();
    TracedMessage& operator=(const TracedMessage& other);
    virtual TracedMessage *dup() const override {return new TracedMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual omnetpp::simtime_t getQueueEnterTime() const;
    virtual void setQueueEnterTime(omnetpp::simtime_t queueEnterTime);

    virtual omnetpp::simtime_t getQueueLeaveTime() const;
    virtual void setQueueLeaveTime(omnetpp::simtime_t queueLeaveTime);

    virtual omnetpp::simtime_t getFinishedTime() const;
    virtual void setFinishedTime(omnetpp::simtime_t finishedTime);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const TracedMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, TracedMessage& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline TracedMessage *fromAnyPtr(any_ptr ptr) { return check_and_cast<TracedMessage*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __TRACEDMESSAGE_M_H

